const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
const ADD_TO_CART = "ADD_TO_CART";
const CHANGE_QUANTITY = "CHANGE_QUANTITY";
const DELETE_CART_ITEM = "DELETE_CART_ITEM"
const OPEN_SIDEBAR="OPEN_SIDEBAR"
const CLOSE_SIDEBAR="CLOSE_SIDEBAR"


export {
  GET_PRODUCT_FAILURE,
  GET_PRODUCT_REQUEST,
  GET_PRODUCT_SUCCESS,
  ADD_TO_CART,
  CHANGE_QUANTITY,
  DELETE_CART_ITEM,
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR
};
